<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FreshMart.Notification.Domain\FreshMart.Notification.Domain.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\FreshMart.Shared.Core\FreshMart.Shared.Core.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\FreshMart.Shared.Validation\FreshMart.Shared.Validation.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
