<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FreshMart.Ordering.Application\FreshMart.Ordering.Application.csproj" />
    <ProjectReference Include="..\FreshMart.Ordering.Domain\FreshMart.Ordering.Domain.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\FreshMart.Shared.Persistence\FreshMart.Shared.Persistence.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\FreshMart.Shared.Messaging\FreshMart.Shared.Messaging.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\FreshMart.Shared.Contracts\FreshMart.Shared.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
